version: "3"

services:
  db_xia_jobs:
    image: mysql:8.0.36
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_HOST: ''
    networks:
      - openlxp

  app_xia_jobs:
    build:
      context: .
    ports:
      - "8000:8020"
    command: >
      sh -c ". /opt/app/start-app.sh"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
      CSRF_COOKIE_DOMAIN: "${CSRF_COOKIE_DOMAIN}"
      CSRF_TRUSTED_ORIGINS: "${CSRF_TRUSTED_ORIGINS}"
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      DB_USER: "${DB_USER}"
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
      DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
      LOG_PATH: "${LOG_PATH}"
      SECRET_KEY_VAL: "${SECRET_KEY_VAL}"
    volumes:
      - ./app:/opt/app/edlm-xia-jobs
    depends_on:
      - db_xia_jobs
    networks:
      - openlxp

  redis:
    image: redis:alpine
    networks:
      - openlxp

  celery:
    build:
      context: .
    command: celery -A edlm_xia_jobs_project worker -l info --pool=solo
    volumes:
      - ./app:/opt/app/edlm-xia-jobs
    environment:
      REQUESTS_CA_BUNDLE: '/etc/ssl/certs/ca-certificates.crt'
      AWS_CA_BUNDLE: '/etc/ssl/certs/ca-certificates.crt'
    env_file:
      - ./.env
    depends_on:
      - db_xia_jobs
      - redis
      - app_xia_jobs
    networks:
      - openlxp
    restart: on-failure

  celery-beat:
    build:
      context: .
    command: celery -A edlm_xia_jobs_project beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info --pidfile=/tmp/celerybeat.pid
    volumes:
      - ./app:/opt/app/edlm-xia-jobs
    environment:
      REQUESTS_CA_BUNDLE: '/etc/ssl/certs/ca-certificates.crt'
      AWS_CA_BUNDLE: '/etc/ssl/certs/ca-certificates.crt'
    env_file:
      - ./.env
    depends_on:
      - db_xia_jobs
      - redis
      - app_xia_jobs
    networks:
      - openlxp
    restart: on-failure

#  flower:
#    image: mher/flower:0.9.7
#    command: [ "flower", "--broker=redis://redis:6379/0", "--port=8888" ]
#    ports:
#      - 8888:8888
#    networks:
#      - openlxp

networks:
  openlxp:
    external: true
