# Generated by Django 3.2.25 on 2024-06-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_xsrconfiguration_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xsrconfiguration',
            name='token',
            field=models.CharField(help_text='Enter the XSR Token', max_length=200),
        ),
    ]
